### ISSUE TITLE
Training

### ISSUE THREAD

**Issue by rhobro** [webonnx/wonnx#100]
**Is your feature request related to a problem? Please describe.**
I am trying to develop a ml project which is supposed to run on Rust. In order to allow model portability, onnx was chosen. 

Does wonnx plan to allow training in the future? This would be very useful because otherwise, people may have to rewrite or interface their rust code in python to allow training with python based frameworks.

**Describe the solution you'd like**
A way to formulate and train the onnx model and save it.

**Describe alternatives you've considered**
Tract and onnxruntime-rs were identified as the main contenders. However, tract was meant for embedded devices and was not GPU-accelerated, onnxruntime-rs would not build and did not support the latest version of onnxruntime. Both didn't support training.

**Additional context**

**Comment by pixelspark** [comment]
@rhobro thank you for your interest in wonnx! 

Being able to train models would be great indeed - it would allow users to 'close the loop' and use ONNX-based ML without relying on Python, on many platforms (possibly even the web). At this point however, training models is not an end goal we are pursuing. We are still miles away from actually being able to do inference on ONNX models (let alone do it in a performant way). It would probably take a large effort to change the architecture to allow for training.

**Comment by pixelspark** [comment]
I can't back this up with numbers, but my expectation is that TensorFlow and Torch will be fast for inference if they can use the GPU (this typically requires your PC to have NVIDIA hardware, CUDA, etc.). There are also ways to run TensorFlow on Apple hardware (tensorflow-apple) or AMD (through ROCm). 

Wonnx is a good option when you do have a GPU but it's not NVIDIA (or it is but you can't get CUDA to work, e.g. on older Macs). It will not outperform TensorFlow/Torch on GPU but it will likely outperform TensorFlow/Torch on CPU for larger models. Wonnx is not fully compliant yet though.

As for tract - it uses CPU only and is optimized for latency rather than throughput (e.g. for wake-word models and such). It will generally give you good performance and good latency on smaller models (in some cases better than GPU-based engines), but will be very slow on larger ones.

**Comment by rhobro** [comment]
Ok thanks for this.

How does wonnx access the GPU if it's a wasm program?

**Comment by pixelspark** [comment]
> Ok thanks for this.
> 
> How does wonnx access the GPU if it's a wasm program?

Wonnx can be run as WASM in the browser, and it will use the browser-provided WebGPU API to access the GPU.

**Comment by rhobro** [comment]
I see. Does the webgpu api also work when the programs are not run in the browser?

**Comment by pixelspark** [comment]
> I see. Does the webgpu api also work when the programs are not run in the browser?

Wonnx uses the wgpu create, which provides an interface resembling WebGPU. When run in the browser, wgpu mostly forwards all requests to the browser's WebGPU implementation.

When run natively, wgpu will forward to either Vulkan, Metal or DirectX depending on the platform (see README).
