### ISSUE TITLE
Can't run any Model via WebGPU + WASM on Chrome

### ISSUE THREAD

**Issue by nebea** [webonnx/wonnx#131]
## Description
I could not run even a single model via WebGPU WASM. I tried to run squeeze.html or single_relu or any other self simplified .onnx. I always get a lot of warnings while initializing the model. And when I run an inference, I'm getting the correct tensor shape, but all values with 0. 

`Tint WGSL reader failure: :11:8 error: invalid type for struct member`

## Reproduce
Following the description for the examples. Using latest chrome canary

## Expected Behaviour
A correct Tensor after inferencing. 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS 12.6 (i7, MBP16, 2019, base model)
 - Browser Chrome Canary
 - Version 109.0.5388.0

**Comment by pixelspark** [comment]
The problem seems to be that WGSL has evolved significantly and wgpu's implementation was lagging quite a bit until recently. Unfortunately switching to the new wgpu version and updating the shaders still doesn't fix running on the web because of an issue in wgpu (see https://github.com/webonnx/wonnx/pull/140). Once that PR lands your issue should be fixed.

**Comment by pixelspark** [comment]
Latest master should work again (with some warnings). I just tested the 'squeeze'  example in Chrome Canary. After #140 and #142 have merged, things should be smooth again.
